<?php
if (!app()->auth::check()):
   ?>
    <div class="cont">
        <div class="disciplines_1">
            <h3>Дисциплины</h3>
            <div class="disciplines_menu_vibor">Экология</div>
            <div class="disciplines_menu_1">Биология</div>
            <div class="disciplines_menu_1">География</div>
            <div class="disciplines_menu_1">ПИДИС</div>
            <div class="disciplines_menu_1">РКиС</div>
            <div class="disciplines_menu_1">Философия</div>
            <div class="disciplines_menu_1">Анатомия</div>
            <div class="disciplines_menu_1">Мат. анализ</div>
            <div class="disciplines_menu_1">История</div>
            <div class="disciplines_menu_1">Физкультура</div>
            <div class="disciplines_menu_1">ПИРВП</div>
        </div>
        <div class="attendance_1">
            <div class="groups_choice_1">
                <h2>Группы</h2>
                <div class="group_student_1">323</div>
                <div class="group_student_1">345</div>
                <div class="group_student_1">754</div>
                <div class="group_student_1">785</div>
                <div class="group_student_1">843</div>
                <div class="group_student_1">564</div>
                <div class="group_student_1">124</div>
                <div class="group_student_1">242</div>
                <div class="group_student_1">245</div>
                <div class="group_student_1">746</div>
            </div>
            <div class="attendance_month_1">
                <h2>Текущая посещаемость</h2>
                <!-- <div class="attendance_student">.</div> -->
                <table  border="1" cellPadding="10" cellSpacing="2" align="center">
                    <tbody>
                        <tr>
                            <th colspan="2">Губарь Татьяна Евгеньевна</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Зеленина Алёна Олеговна</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Гришаненко Владислав Евгеньевич</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Корчагина Алина Алексеевна</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Иванов Иван Петрович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th colspan="2">Трут Александр Романович</th>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                            <td>*</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>н</td>
                            <td>*</td>
                            <td>*</td>
                        </tr>
                    </tbody>
                        
                </table>
            </div>
        </div>
    </div>
<?php endif;